### ISSUE TITLE
请问这个固件可以用于红蜂小四（半入耳）吗？

### ISSUE THREAD

**Issue by weachy** [gekowa/BES-Firmwares#1]
如题，想比葫芦画瓢，可到处也没找到适用于四代的固件。期望得到解惑，感谢

**Comment by gekowa** [comment]
刷完之后，可能会被认成Pro 3代，某些功能可能会工作不正常，如降噪、透传。
但如果你也被最大音量bug困扰，也许可以考虑一试，死马当活马医。

在尝试之前，我建议你保存原固件，并给这个repo推一个PR，谢谢。

**Comment by weachy** [comment]
非常感谢，已经刷入。耳机变成pro了，不过除了降噪外功能正常
